const sports=[['🏏','Box Cricket'],['🏏','Cricket'],['⚽','Football'],['🏸','Badminton'],['🏊','Swimming'],['🏓','Pickleball'],['🏀','Basketball'],['🏐','Volleyball'],['🎮','Game Zone'],['🏡','Farmhouse'],['🎾','Tennis'],['🏃','Fitness']];
// Sample listings and availability are illustrative until connected to a venue inventory service.
const venues=[
{name:'Smash Arena Box Cricket',type:'Box Cricket',city:'Gachibowli, Hyderabad',rating:4.8,price:800,img:'assets/venue-box-cricket.png',tag:'Popular',amenities:['Floodlights','Parking','Changing rooms','Air conditioning'],review:'“Great turf and easy parking.”',reviews:128,cancel:'Free cancellation up to 24 hours before play.'},
{name:'Ace Badminton Club',type:'Badminton',city:'Madhapur, Hyderabad',rating:4.7,price:550,img:'assets/venue-badminton.png',tag:'Top rated',amenities:['Wooden courts','Parking','Changing rooms','Air conditioning'],review:'“Clean courts and helpful staff.”',reviews:96,cancel:'Free cancellation up to 12 hours before play.'},
{name:'Urban Football Arena',type:'Football',city:'Kondapur, Hyderabad',rating:4.6,price:1200,img:'assets/venue-football.png',tag:'Trending',amenities:['Floodlights','Parking','Changing rooms'],review:'“Plenty of space for a full game.”',reviews:74,cancel:'Cancellation terms are illustrative in this demo.'},
{name:'BlueWave Swimming Club',type:'Swimming',city:'Jubilee Hills, Hyderabad',rating:4.5,price:450,img:'assets/venue-swimming.png',tag:'Popular',amenities:['Pool access','Showers','Changing rooms','Air conditioning'],review:'“Friendly coaches and a lovely pool.”',reviews:112,cancel:'Free cancellation up to 12 hours before play.'},
{name:'PicklePro Courts',type:'Pickleball',city:'HITEC City, Hyderabad',rating:4.8,price:700,img:'assets/venue-pickleball.png',tag:'New',amenities:['Court hire','Equipment rental','Parking','Air conditioning'],review:'“Excellent surface and new equipment.”',reviews:38,cancel:'Cancellation terms are illustrative in this demo.'},
{name:'The Game District',type:'Game Zone',city:'Banjara Hills, Hyderabad',rating:4.6,price:399,img:'assets/venue-gamezone.png',tag:'Family',amenities:['Arcade games','Food available','Parking'],review:'“A fun spot for a group outing.”',reviews:63,cancel:'Free cancellation up to 12 hours before play.'}
];
const sportGrid=document.getElementById('sportGrid'),filters=document.getElementById('filters'),venueGrid=document.getElementById('venueGrid'),resultText=document.getElementById('resultText');
let selectedVenue=null,selectedSlot=null,activeType='All';
const times=['6:00 AM','7:00 AM','8:00 AM','9:00 AM','5:00 PM','6:00 PM','7:00 PM','8:00 PM','9:00 PM'];
sportGrid.innerHTML=sports.map(([emoji,name])=>`<button class="sport-card" data-sport="${name}"><span class="emoji">${emoji}</span><b>${name}</b></button>`).join('');
const filterNames=['All','Box Cricket','Badminton','Football','Swimming','Pickleball'];
filters.innerHTML=filterNames.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('');
function render(list){
 if(!list.length){venueGrid.innerHTML='<div class="empty-state"><h3>No venues match these choices yet</h3><p>Try another sport, a higher price limit, or a nearby Hyderabad locality.</p><button class="clear-filters">Clear filters</button></div>';venueGrid.querySelector('.clear-filters').addEventListener('click',clearFilters);return}
 venueGrid.innerHTML=list.map(v=>`<article class="venue-card"><div class="venue-photo" role="img" aria-label="Sample photo for ${v.name}" style="background-image:url('${v.img}')"><span class="tag">Sample listing</span><button class="heart" aria-label="Save ${v.name}" aria-pressed="false">♡</button></div><div class="venue-body"><div class="venue-name">${v.name}</div><div class="venue-meta">${v.city} · <span class="rating">Example rating ★ ${v.rating.toFixed(1)}</span></div><p class="review-snippet">Example review: ${v.review.replace(/[“”]/g,'')}</p><div class="amenities">${v.amenities.slice(0,3).map(a=>`<span>${a}</span>`).join('')}</div><div class="venue-policy">${v.cancel}</div><div class="price-row"><span class="price">₹${v.price} <small>/ hour · example</small></span><button class="book" data-book="${venues.indexOf(v)}">Preview slots</button></div></div></article>`).join('');
 venueGrid.querySelectorAll('.book').forEach(b=>b.addEventListener('click',()=>openBooking(Number(b.dataset.book))));
 venueGrid.querySelectorAll('.heart').forEach(b=>b.addEventListener('click',()=>{const saved=b.textContent==='♡';b.textContent=saved?'♥':'♡';b.setAttribute('aria-pressed',String(saved))}));
}
function apply(){
 const location=document.getElementById('location').value.trim(),q=location.toLowerCase(),max=Number(document.getElementById('maxPrice').value)||Infinity,min=Number(document.getElementById('minRating').value),needAmenity=document.getElementById('amenityFilter').checked;
 let list=venues.filter(v=>(activeType==='All'||v.type===activeType)&&(q===''||q==='hyderabad'||v.city.toLowerCase().includes(q))&&v.price<=max&&v.rating>=min&&(!needAmenity||v.amenities.includes('Air conditioning')));
 const sort=document.getElementById('sortBy').value;if(sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);
 const suffix=document.getElementById('searchTime').value?` · time preview: ${document.getElementById('searchTime').value}`:'';
 resultText.textContent=`${list.length} sample venue${list.length===1?'':'s'} near ${location||'Hyderabad'} · example data${suffix}`;render(list);
}
function chooseType(type){activeType=type;filters.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===type));apply()}
function clearFilters(){document.getElementById('location').value='Hyderabad';document.getElementById('sport').value='All activities';document.getElementById('maxPrice').value='';document.getElementById('minRating').value='0';document.getElementById('sortBy').value='recommended';document.getElementById('amenityFilter').checked=false;document.getElementById('searchTime').value='';chooseType('All')}
filters.addEventListener('click',e=>{if(e.target.matches('.filter'))chooseType(e.target.dataset.filter)});
sportGrid.addEventListener('click',e=>{const card=e.target.closest('.sport-card');if(!card)return;document.getElementById('sport').value=card.dataset.sport;chooseType(card.dataset.sport);document.getElementById('venues').scrollIntoView({behavior:'smooth'})});
document.getElementById('searchBtn').addEventListener('click',()=>{const type=document.getElementById('sport').value;chooseType(type==='All activities'?'All':type);document.getElementById('venues').scrollIntoView({behavior:'smooth'})});
['maxPrice','minRating','sortBy','amenityFilter'].forEach(id=>document.getElementById(id).addEventListener('change',apply));
const modal=document.getElementById('bookingModal'),ownerModal=document.getElementById('ownerModal');let lastFocused=null;
function showModal(target){lastFocused=document.activeElement;target.classList.add('open');target.querySelector('[data-close]').focus()}
function closeModal(target){target.classList.remove('open');if(lastFocused?.focus)lastFocused.focus()}
function hour24(label){const [clock,period]=label.split(' ');let [hour]=clock.split(':').map(Number);if(period==='AM'&&hour===12)hour=0;if(period==='PM'&&hour!==12)hour+=12;return hour}
function hourLabel(hour){const period=hour>=12?'PM':'AM',display=hour%12||12;return `${display}:00 ${period}`}
function renderBookingSlots(){if(!selectedVenue)return;selectedSlot=null;const duration=Number(document.getElementById('duration').value),slotList=document.getElementById('slots');document.getElementById('chosen').textContent='None';document.getElementById('durationSummary').textContent=`${duration} ${duration===1?'hour':'hours'}`;document.getElementById('amount').textContent='₹0';document.getElementById('slotHeading').textContent=`Example start times · ${duration}-hour booking`;slotList.innerHTML=times.filter(t=>{const h=hour24(t);return (h<12?h+duration<=10:h+duration<=22)}).map(t=>{const end=hourLabel(hour24(t)+duration);return `<button class="slot" aria-pressed="false" data-start="${t}" data-end="${end}">${t} – ${end}<small>Example · not live</small></button>`}).join('');slotList.querySelectorAll('.slot').forEach(s=>s.addEventListener('click',()=>{slotList.querySelectorAll('.slot').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});s.classList.add('selected');s.setAttribute('aria-pressed','true');selectedSlot={start:s.dataset.start,end:s.dataset.end,hours:duration};document.getElementById('chosen').textContent=`${selectedSlot.start} – ${selectedSlot.end}`;document.getElementById('amount').textContent=`₹${selectedVenue.price*duration}`}))}
function openBooking(index){selectedVenue=venues[index];selectedSlot=null;document.getElementById('bookingTitle').textContent=selectedVenue.name;document.getElementById('bookingMeta').textContent=`${selectedVenue.city} · Example rating ★ ${selectedVenue.rating.toFixed(1)} · ₹${selectedVenue.price}/hour example`;document.getElementById('bookingAmenities').textContent=`Sample amenities: ${selectedVenue.amenities.join(' · ')}. Example policy: ${selectedVenue.cancel}`;document.getElementById('bookingDate').value=document.getElementById('date').value;document.getElementById('duration').value='1';renderBookingSlots();showModal(modal)}
document.getElementById('duration').addEventListener('change',renderBookingSlots);
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>{const parent=x.closest('.modal');if(parent)closeModal(parent)}));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
document.addEventListener('keydown',e=>{const open=document.querySelector('.modal.open');if(!open)return;if(e.key==='Escape'){closeModal(open);return}if(e.key==='Tab'){const items=[...open.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
document.getElementById('confirmBooking').addEventListener('click',()=>{if(!selectedSlot){showToast('Choose an example time to preview the total.');return}closeModal(modal);showToast(`Preview only: ${selectedSlot.hours}-hour example, ₹${selectedVenue.price*selectedSlot.hours} total. No booking or payment was made.`)});
function openOwner(){showModal(ownerModal)}document.getElementById('listVenueBtn').addEventListener('click',openOwner);document.getElementById('footerList').addEventListener('click',openOwner);document.getElementById('submitOwner').addEventListener('click',()=>{closeModal(ownerModal);showToast('Preview only: venue details were not submitted or saved.')});
document.getElementById('loginBtn').addEventListener('click',()=>showToast('Demo page: sign-in and OTP are not connected yet.'));
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3800)}
const today=new Date().toISOString().slice(0,10);document.getElementById('date').value=today;document.getElementById('date').min=today;document.getElementById('bookingDate').value=today;document.getElementById('bookingDate').min=today;render(venues);
